Scene: ${Name}
Entities:
  - UUID: 5345347092
    TagComponent:
      Tag: camera
    TransformComponent:
      Position: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    CameraComponent:
      PerspectiveData:
        FOV: 45
        NearClip: 0
        FarClip: 100
      OrthographicData:
        Size: 6
        NearClip: -1
        FarClip: 1
      Type: 0
      Primary: true
      FixedAspectRatio: false