Scene: Scene
Entities:
  - UUID: 14651073086529455734
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [7.5, 21, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteComponent:
      Color: [0, 193, 83, 255]
      TextureHandel: ""
    RigidBody2DComponent:
      Type: 2
      FixedRotatiin: false
    BoxColliderComponent:
      Size: [0.5, 0.5]
      Offset: [0, 0]
      Density: 1
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5
  - UUID: 3013420867993795234
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [-15.6040001, 38.5, 0]
      Rotation: [0, 0, 0]
      Scale: [6.99700022, 12.6049995, 1]
    SpriteComponent:
      Color: [0, 0, 0, 255]
      TextureHandel: ""
    RigidBody2DComponent:
      Type: 2
      FixedRotatiin: false
    BoxColliderComponent:
      Size: [0.5, 0.5]
      Offset: [0, 0]
      Density: 10
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5
  - UUID: 11448996740753184378
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [11.25, 22, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteComponent:
      Color: [135, 255, 212, 255]
      TextureHandel: ""
    RigidBody2DComponent:
      Type: 2
      FixedRotatiin: false
    BoxColliderComponent:
      Size: [0.5, 0.5]
      Offset: [0, 0]
      Density: 1
      Friction: 0.5
      Restitution: 0.5
      RestitutionThreshold: 0.5
  - UUID: 10068557800501391702
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [0, 14.2049999, 0]
      Rotation: [0, 0, 0]
      Scale: [26.6650009, 0.49000001, 1]
    SpriteComponent:
      Color: [69, 82, 0, 255]
      TextureHandel: ""
    RigidBody2DComponent:
      Type: 2
      FixedRotatiin: false
    BoxColliderComponent:
      Size: [0.5, 0.5]
      Offset: [0, 0]
      Density: 1
      Friction: 0.5
      Restitution: 0
      RestitutionThreshold: 0.5
  - UUID: 11902338884230895079
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [0, 7.5, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 12.6789999, 1]
    SpriteComponent:
      Color: [177, 168, 53, 255]
      TextureHandel: ""
    RigidBody2DComponent:
      Type: 0
      FixedRotatiin: false
    BoxColliderComponent:
      Size: [0.5, 0.5]
      Offset: [0, 0]
      Density: 1
      Friction: 0.5
      Restitution: 0
      RestitutionThreshold: 0.5
  - UUID: 3501579656753833202
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [100, 2.148, 1]
    SpriteComponent:
      Color: [100, 0, 0, 255]
      TextureHandel: ""
    RigidBody2DComponent:
      Type: 0
      FixedRotatiin: true
    BoxColliderComponent:
      Size: [0.5, 0.5]
      Offset: [0, 0]
      Density: 1
      Friction: 0.5
      Restitution: 0
      RestitutionThreshold: 0.5
  - UUID: 14367647453350160937
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [0, 24.75, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    CameraComponent:
      PerspectiveData:
        FOV: 45
        NearClip: 0
        FarClip: 100
      OrthographicData:
        Size: 50
        NearClip: -1
        FarClip: 1
      Type: 0
      Primary: true
      FixedAspectRatio: false