Scene: Scene
Entities:
  - UUID: 5345347092
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [0, -4.5, 0]
      Rotation: [0, 0, 0]
      Scale: [24.4960003, 1.10399997, 1]
    SpriteComponent:
      Color: [85, 255, 0, 255]
      TextureHandel: ""
  - UUID: 5345347092
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [0, 5, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    SpriteComponent:
      Color: [255, 0, 0, 255]
      TextureHandel: ""
  - UUID: 5345347092
    TagComponent:
      Tag: Entity
    TransformComponent:
      Position: [0, 0, 0]
      Rotation: [0, 0, 0]
      Scale: [1, 1, 1]
    CameraComponent:
      PerspectiveData:
        FOV: 45
        NearClip: 0
        FarClip: 100
      OrthographicData:
        Size: 16
        NearClip: -1
        FarClip: 1
      Type: 0
      Primary: true
      FixedAspectRatio: false